[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
check_untyped_defs = true
disallow_untyped_defs = true
warn_unused_ignores = true
warn_return_any = true
strict_optional = true
namespace_packages = true

[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
select = ["E", "F", "B", "UP", "N", "I"]
fix = true
exclude = ["TraidingBotAndAnalyticsEvn", ".mypy_cache"]
